### ISSUE TITLE
Unexpected token: punc (:)

### ISSUE THREAD

**Issue by verdi64** [kbond/symfony-grunt-edition#1]
running : grunt
Running "clean:0" (clean) task
Cleaning web/_static/css...OK
Cleaning web/_static/js...OK

Running "jshint:all" (jshint) task

✔ No problems

Running "uglify:build" (uglify) task
File "web/_static/js/script.min.js" created.
Original: 155076 bytes.
Minified: 122047 bytes.

Running "cssmin:build" (cssmin) task
File web/_static/css/style.min.css created.
Original: 149496 bytes.
Minified: 121645 bytes.

Running "modernizr" task

Enabled Extras

> > shiv
> > load
> > cssclasses

Looking for Modernizr references

Downloading source files
404 modernizr.load.1.5.4.js
404 modernizr-latest.js

> > Generating a custom Modernizr build
> > Uglifying
> > Fatal error: Unexpected token: punc (:)

Any hint?

**Comment by kbond** [comment]
Looks like an issue with grunt-modernizr (https://github.com/Modernizr/grunt-modernizr/issues/118)
